import React, { useState, useEffect, useCallback, useRef } from 'react';
import {
  Compass,
  MapPin,
  Calendar,
  RotateCw,
  Moon,
  Sun,
  AlertTriangle,
  CheckCircle,
  ChevronDown,
  ChevronUp,
  Settings,
  Key,
  Hourglass
} from 'lucide-react';

const STORAGE_API_KEY_KEY = "taiwan_birds_ebird_api_key";
const STORAGE_THEME_KEY = "taiwan_birds_theme";
const STORAGE_REGION_STATS_KEY = "taiwan_birds_region_stats";
const STORAGE_REGION_STATS_TIME_KEY = "taiwan_birds_region_stats_time";

// Per-tab storage keys (v4 — bumped to invalidate old caches missing zh names)
const TAB_KEYS = {
  recent: {
    obs: "taiwan_birds_recent_obs_cache_v4",
    days: "taiwan_birds_recent_days_setting",
    time: "taiwan_birds_recent_last_fetch_time_v4",
  },
  notable: {
    obs: "taiwan_birds_notable_obs_cache_v4",
    days: "taiwan_birds_notable_days_setting",
    time: "taiwan_birds_notable_last_fetch_time_v4",
  },
};

const TAB_LABELS = {
  recent: "最近觀察",
  notable: "稀有種快報",
};

const STORAGE_TAXONOMY_KEY = "taiwan_birds_taxonomy_cache_v4";
const STORAGE_TAXONOMY_TIME_KEY = "taiwan_birds_taxonomy_time_v4";

// Static JSON file mapping: tab + days -> filename
// These files are pre-generated by scripts/fetch_birds.py (Hermes cron)
const STATIC_DATA_FILES = {
  recent: { 1: 'recent-1d.json', 2: 'recent-2d.json', 3: 'recent-3d.json', 30: 'recent-cumulative.json' },
  notable: { 7: 'notable-7d.json', 14: 'notable-14d.json', 30: 'notable-30d.json' },
};

// Taiwan subnational1 region codes with display names
const TW_REGIONS = [
  { code: 'TW-TPQ', name: '新北' },
  { code: 'TW-TPE', name: '台北' },
  { code: 'TW-TAO', name: '桃園' },
  { code: 'TW-HSZ', name: '新竹市' },
  { code: 'TW-HSQ', name: '新竹縣' },
  { code: 'TW-MIA', name: '苗栗' },
  { code: 'TW-TXG', name: '台中' },
  { code: 'TW-CHA', name: '彰化' },
  { code: 'TW-YUN', name: '雲林' },
  { code: 'TW-CYQ', name: '嘉義縣' },
  { code: 'TW-CYI', name: '嘉義市' },
  { code: 'TW-TNN', name: '台南' },
  { code: 'TW-KHH', name: '高雄' },
  { code: 'TW-PIF', name: '屏東' },
  { code: 'TW-ILA', name: '宜蘭' },
  { code: 'TW-HUA', name: '花蓮' },
  { code: 'TW-TTT', name: '台東' },
  { code: 'TW-PEN', name: '澎湖' },
  { code: 'TW-KIN', name: '金門' },
  { code: 'TW-LIE', name: '馬祖' },
  { code: 'TW-NAN', name: '南投' },
  { code: 'TW-KEE', name: '基隆' },
];

const TW_REGION_MAP = Object.fromEntries(TW_REGIONS.map(r => [r.code, r.name]));

const STORAGE_SELECTED_REGIONS_KEY = "taiwan_birds_selected_regions";

export default function App() {
  const [activeTab, setActiveTab] = useState('notable');

  // Taxonomy info map: speciesCode -> { taxonOrder, order, familyComName }
  const [taxonomyOrder, setTaxonomyOrder] = useState(() => {
    try {
      const cached = localStorage.getItem(STORAGE_TAXONOMY_KEY);
      if (cached) {
        const obj = JSON.parse(cached);
        if (obj && typeof obj === 'object') return obj;
      }
    } catch { /* ignore */ }
    return null;
  });

  // Load API Key from localStorage
  const [apiKey, setApiKey] = useState(() => {
    return localStorage.getItem(STORAGE_API_KEY_KEY) || '';
  });
  const [inputApiKey, setInputApiKey] = useState(apiKey);
  const [apiKeySavedMsg, setApiKeySavedMsg] = useState('');

  // Per-tab state
  const [tabState, setTabState] = useState({
    recent: { observations: [], loading: false, error: null, days: 1, lastUpdated: null, loaded: false },
    notable: { observations: [], loading: false, error: null, days: 7, lastUpdated: null, loaded: false },
  });

  // Month species count
  const [monthSpeciesCount, setMonthSpeciesCount] = useState(null);

  const [theme, setTheme] = useState(() => {
    return localStorage.getItem(STORAGE_THEME_KEY) || 'dark';
  });

  // Accordion state
  const [expandedSpecies, setExpandedSpecies] = useState(new Set());
  const [expandedCounty, setExpandedCounty] = useState(null);
  const [showSettings, setShowSettings] = useState(false);

  // Settings Accordion Sections Open/Closed state
  const [openSettingsSections, setOpenSettingsSections] = useState({
    key: false,
    region: false,
    update: false,
  });

  const toggleSettingsSection = (sectionKey) => {
    setOpenSettingsSections(prev => ({
      ...prev,
      [sectionKey]: !prev[sectionKey]
    }));
  };

  // Helper to filter observations by selected regions (supporting TW-codes and county names)
  const isObsInSelectedRegions = (obs, selectedCodes) => {
    if (!selectedCodes || selectedCodes.length === 0) return true;
    if (obs.subnational1Code && selectedCodes.includes(obs.subnational1Code)) return true;
    const loc = obs.locName || '';
    for (const code of selectedCodes) {
      if (loc.includes(code)) return true;
      const name = TW_REGION_MAP[code];
      if (name) {
        if (loc.includes(name)) return true;
        if (name.startsWith('台') && loc.includes(name.replace('台', '臺'))) return true;
        if (name.startsWith('臺') && loc.includes(name.replace('臺', '台'))) return true;
      }
    }
    return false;
  };

  // Selected regions for recent tab (max 6)
  const [selectedRegions, setSelectedRegions] = useState(() => {
    try {
      const cached = localStorage.getItem(STORAGE_SELECTED_REGIONS_KEY);
      if (cached) {
        const arr = JSON.parse(cached);
        if (Array.isArray(arr)) return arr.slice(0, 6);
      }
    } catch { /* ignore */ }
    return [];
  });

  // Confirm dialog for update
  const [showUpdateConfirm, setShowUpdateConfirm] = useState(false);

  const toggleRegion = (code) => {
    setSelectedRegions(prev => {
      if (prev.includes(code)) {
        const next = prev.filter(c => c !== code);
        localStorage.setItem(STORAGE_SELECTED_REGIONS_KEY, JSON.stringify(next));
        return next;
      }
      if (prev.length >= 6) return prev; // max 6
      const next = [...prev, code];
      localStorage.setItem(STORAGE_SELECTED_REGIONS_KEY, JSON.stringify(next));
      return next;
    });
  };

  // Track original regions to detect changes on close
  const originalRegionsRef = useRef(selectedRegions);

  const handleOpenSettings = () => {
    originalRegionsRef.current = [...selectedRegions];
    setShowSettings(true);
  };

  const handleCloseSettings = () => {
    setShowSettings(false);
    // If regions changed and on recent tab, clear cache and refetch/filter
    const changed = JSON.stringify(originalRegionsRef.current) !== JSON.stringify(selectedRegions);
    if (changed && activeTab === 'recent') {
      localStorage.removeItem(TAB_KEYS.recent.obs);
      localStorage.removeItem(TAB_KEYS.recent.time);
      if (apiKey && selectedRegions.length > 0) {
        fetchObservations('recent', tabState.recent.days, apiKey);
      }
    }
  };

  const updateTab = (tab, patch) => {
    setTabState(prev => ({
      ...prev,
      [tab]: { ...prev[tab], ...patch },
    }));
  };

  // Initialize Theme
  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme);
    localStorage.setItem(STORAGE_THEME_KEY, theme);
  }, [theme]);

  // Register Service Worker
  useEffect(() => {
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', async () => {
        try {
          const registration = await navigator.serviceWorker.register('/sw.js');
          console.log('[App] ServiceWorker registered: ', registration.scope);
        } catch (err) {
          console.error('[App] ServiceWorker failed: ', err);
        }
      });
    }
  }, []);

  // Fetch taxonomy order map (cache for 30 days) — uses locale=zh for Chinese names
  const fetchTaxonomy = useCallback(async (activeKey = apiKey) => {
    if (!activeKey) return;
    // Check cache age (30 days)
    const cachedTime = localStorage.getItem(STORAGE_TAXONOMY_TIME_KEY);
    if (cachedTime) {
      const age = Date.now() - new Date(cachedTime).getTime();
      if (age < 30 * 24 * 60 * 60 * 1000 && taxonomyOrder) return;
    }
    try {
      const headers = { 'x-ebirdapitoken': activeKey };
      const url = 'https://api.ebird.org/v2/ref/taxonomy/ebird?fmt=json&locale=zh';
      const res = await fetch(url, { headers });
      if (!res.ok) return;
      const data = await res.json();
      const orderMap = {};
      (Array.isArray(data) ? data : []).forEach(item => {
        if (item.speciesCode && item.taxonOrder != null) {
          orderMap[item.speciesCode] = {
            taxonOrder: item.taxonOrder,
            order: item.order || '',
            familyComName: item.familyComName || '',
            comNameZh: item.comName || '',
          };
        }
      });
      setTaxonomyOrder(orderMap);
      localStorage.setItem(STORAGE_TAXONOMY_KEY, JSON.stringify(orderMap));
      localStorage.setItem(STORAGE_TAXONOMY_TIME_KEY, new Date().toISOString());
    } catch (err) {
      console.error("Fetch taxonomy failed:", err);
    }
  }, [apiKey, taxonomyOrder]);

  // Fetch this month's unique species count
  const fetchMonthSpecies = useCallback(async (activeKey = apiKey) => {
    if (!activeKey) return;
    try {
      const headers = { 'x-ebirdapitoken': activeKey };
      const now = new Date();
      const backDays = Math.min(now.getDate(), 30);
      const url = `https://api.ebird.org/v2/data/obs/TW/recent?back=${backDays}&detail=simple`;
      const res = await fetch(url, { headers });
      const data = res.ok ? await res.json() : [];
      const count = Array.isArray(data) ? data.length : 0;
      setMonthSpeciesCount(count);
      localStorage.setItem(STORAGE_REGION_STATS_KEY, JSON.stringify({ monthSpecies: count }));
      localStorage.setItem(STORAGE_REGION_STATS_TIME_KEY, new Date().toISOString());
    } catch (err) {
      console.error("Fetch month species failed:", err);
    }
  }, [apiKey]);

  // Main API Fetch function — works for both tabs with AbortController & 2.5s safe delay
  const abortControllerRef = useRef(null);

  const fetchObservations = useCallback(async (tab, selectedDays, activeKey = apiKey) => {
    if (!activeKey) {
      updateTab(tab, { error: "請先設定您的 eBird API Key。", loading: false });
      return;
    }

    // Cancel previous in-flight requests to prevent rate limit collisions
    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
    }
    const controller = new AbortController();
    abortControllerRef.current = controller;

    updateTab(tab, { loading: true, error: null });

    try {
      const notable = tab === 'notable';
      const headers = { 'x-ebirdapitoken': activeKey };

      let dataEn = [];
      let dataZh = [];

      if (notable) {
        // Notable: single API call for all of Taiwan (returns multiple records per species)
        const basePath = `https://api.ebird.org/v2/data/obs/TW/recent/notable`;
        const urlEn = `${basePath}?back=${selectedDays}&detail=simple&includeProvisional=true`;
        const urlZh = `${basePath}?back=${selectedDays}&detail=simple&includeProvisional=true&sppLocale=zh`;

        const [resEn, resZh] = await Promise.all([
          fetch(urlEn, { headers, signal: controller.signal }),
          fetch(urlZh, { headers, signal: controller.signal })
        ]);

        if (!resEn.ok || !resZh.ok) {
          throw new Error(`eBird API error: ${resEn.status} / ${resZh.status}`);
        }

        dataEn = await resEn.json();
        dataZh = await resZh.json();
      } else {
        // Recent: fetch user-selected regions with 2.5s delay & 4s/8s/12s 429 backoff
        const regionsToFetch = selectedRegions.length > 0
          ? selectedRegions
          : TW_REGIONS.map(r => r.code);

        const fetchWithRetry = async (url, maxRetries = 3) => {
          for (let attempt = 0; attempt <= maxRetries; attempt++) {
            if (controller.signal.aborted) return [];
            try {
              const res = await fetch(url, { headers, signal: controller.signal });
              if (res.status === 429) {
                await new Promise(r => setTimeout(r, 4000 * (attempt + 1)));
                continue;
              }
              if (!res.ok) return [];
              return await res.json();
            } catch (e) {
              if (e.name === 'AbortError') return [];
              if (attempt < maxRetries) {
                await new Promise(r => setTimeout(r, 3000 * (attempt + 1)));
                continue;
              }
              return [];
            }
          }
          return [];
        };

        // Fetch with sppLocale=zh sequentially (2.5s delay to safely prevent 429 rate limits)
        dataEn = [];
        for (const r of regionsToFetch) {
          if (controller.signal.aborted) break;
          const url = `https://api.ebird.org/v2/data/obs/${r}/recent?back=${selectedDays}&detail=simple&includeProvisional=true&sppLocale=zh`;
          const result = await fetchWithRetry(url);
          dataEn = dataEn.concat(result);
          await new Promise(r => setTimeout(r, 2500));
        }
        dataZh = [];
      }

      if (controller.signal.aborted) return;

      // Build zh name map from zh data
      const zhNamesMap = {};
      dataZh.forEach(item => {
        if (item.speciesCode && !zhNamesMap[item.speciesCode]) {
          zhNamesMap[item.speciesCode] = item.comName;
        }
      });

      // Fallback: fill missing zh names from taxonomy cache (locale=zh)
      let taxonomyZhMap = null;
      try {
        const cachedTaxonomy = localStorage.getItem(STORAGE_TAXONOMY_KEY);
        if (cachedTaxonomy) {
          const parsed = JSON.parse(cachedTaxonomy);
          if (parsed && typeof parsed === 'object') taxonomyZhMap = parsed;
        }
      } catch { /* ignore */ }
      const mergedList = dataEn.map(item => {
        let zhName = zhNamesMap[item.speciesCode];
        if (!zhName && item.comName && /[\u4e00-\u9fa5]/.test(item.comName)) {
          zhName = item.comName;
        }
        if (!zhName && taxonomyZhMap && taxonomyZhMap[item.speciesCode]) {
          zhName = taxonomyZhMap[item.speciesCode].comNameZh;
        }
        return {
          ...item,
          comNameZh: zhName || item.comName,
          comNameEn: item.comName
        };
      });

      const nowStr = new Date().toISOString();
      const keys = TAB_KEYS[tab];

      updateTab(tab, {
        observations: mergedList,
        loading: false,
        error: null,
        lastUpdated: nowStr,
        loaded: true,
      });

      localStorage.setItem(keys.obs, JSON.stringify(mergedList));
      localStorage.setItem(keys.time, nowStr);
      localStorage.setItem(keys.days, selectedDays.toString());

    } catch (err) {
      if (err.name === 'AbortError') return;
      console.error(`Fetch ${tab} failed:`, err);

      // Graceful Fallback: keep existing observations if present
      setTabState(prev => {
        const existingObs = prev[tab].observations;
        if (existingObs && existingObs.length > 0) {
          return {
            ...prev,
            [tab]: { ...prev[tab], loading: false, error: null }
          };
        }
        return {
          ...prev,
          [tab]: { ...prev[tab], loading: false, error: "無法取得最新線上觀測資料，請點擊設定重試。" }
        };
      });
    }
  }, [apiKey, selectedRegions]);

  // Auto-fetch month species count (once per day cache)
  useEffect(() => {
    if (!apiKey) return;
    const cachedStats = localStorage.getItem(STORAGE_REGION_STATS_KEY);
    const cachedTime = localStorage.getItem(STORAGE_REGION_STATS_TIME_KEY);
    if (cachedStats && cachedTime) {
      const parsedTime = new Date(cachedTime);
      const today = new Date();
      if (
        parsedTime.getFullYear() === today.getFullYear() &&
        parsedTime.getMonth() === today.getMonth() &&
        parsedTime.getDate() === today.getDate()
      ) {
        try {
          const obj = JSON.parse(cachedStats);
          setMonthSpeciesCount(obj.monthSpecies ?? null);
          return;
        } catch { /* fall through */ }
      }
    }
    fetchMonthSpecies(apiKey);
  }, [apiKey]); // eslint-disable-line react-hooks/exhaustive-deps

  // Load static JSON data (generated by cron job, near-instant)
  const loadStaticData = useCallback(async (tab, days) => {
    const fileMap = STATIC_DATA_FILES[tab];
    if (!fileMap || !fileMap[days]) return null;
    try {
      const res = await fetch(`${import.meta.env.BASE_URL}data/${fileMap[days]}`);
      if (!res.ok) return null;
      const data = await res.json();
      if (!Array.isArray(data) || data.length === 0) return null;
      return data;
    } catch {
      return null;
    }
  }, []);

  // Auto-load: 1. Instant static JSON hydration (< 50ms)
  // 2. Check localStorage cache (< 3 hours)
  // 3. Background live API fetch with 2.5s safe delay
  useEffect(() => {
    if (!apiKey) return; // Require API key before loading any data

    let cancelled = false;

    const run = async () => {
      const tab = activeTab;
      const current = tabState[tab];
      const keys = TAB_KEYS[tab];

      // Check localStorage cache age (3 hours limit)
      const cachedObs = localStorage.getItem(keys.obs);
      const cachedTime = localStorage.getItem(keys.time);
      const cachedDays = localStorage.getItem(keys.days);

      if (cachedObs && cachedTime && cachedDays === current.days.toString()) {
        const ageMs = Date.now() - new Date(cachedTime).getTime();
        const THREE_HOURS_MS = 3 * 60 * 60 * 1000;
        if (ageMs < THREE_HOURS_MS) {
          try {
            const parsedObs = JSON.parse(cachedObs);
            updateTab(tab, {
              observations: parsedObs,
              lastUpdated: cachedTime,
              loaded: true,
              loading: false,
            });
            return;
          } catch { /* ignore error and fallback */ }
        }
      }

      // Instant hydration: try Vercel static JSON first for zero-delay rendering
      const staticData = await loadStaticData(tab, current.days);
      if (cancelled) return;

      if (staticData && staticData.length > 0) {
        updateTab(tab, {
          observations: staticData,
          loading: false,
          error: null,
          lastUpdated: new Date().toISOString(),
          loaded: true,
        });
      } else {
        updateTab(tab, { loading: true, error: null });
      }

      // Background live API fetch with 2.5s safe delay
      await fetchTaxonomy(apiKey);
      if (cancelled) return;
      await fetchObservations(tab, current.days, apiKey);
    };

    run();

    return () => { cancelled = true; };
  }, [apiKey, activeTab, tabState.recent.days, tabState.notable.days, selectedRegions]); // eslint-disable-line react-hooks/exhaustive-deps

  const handleSearchClick = () => {
    if (!apiKey) {
      setShowSettings(true);
      return;
    }
    // Show confirmation dialog before starting update
    setShowUpdateConfirm(true);
  };

  const confirmUpdate = () => {
    setShowUpdateConfirm(false);
    fetchObservations(activeTab, tabState[activeTab].days, apiKey);
  };

  const saveApiKey = (keyToSave = inputApiKey) => {
    const trimmed = keyToSave.trim();
    setApiKey(trimmed);
    localStorage.setItem(STORAGE_API_KEY_KEY, trimmed);
    setApiKeySavedMsg("API Key 儲存成功！正在獲取觀測資料...");
    setTimeout(() => setApiKeySavedMsg(''), 3000);
    if (trimmed) {
      fetchTaxonomy(trimmed).then(() => {
        fetchObservations('recent', tabState.recent.days, trimmed);
        fetchObservations('notable', tabState.notable.days, trimmed);
      });
      fetchMonthSpecies(trimmed);
    }
  };

  const clearApiKey = () => {
    setApiKey('');
    setInputApiKey('');
    setTabState({
      recent: { observations: [], loading: false, error: null, days: 1, lastUpdated: null, loaded: false },
      notable: { observations: [], loading: false, error: null, days: 7, lastUpdated: null, loaded: false },
    });
    setMonthSpeciesCount(null);
    setTaxonomyOrder(null);
    localStorage.removeItem(STORAGE_API_KEY_KEY);
    localStorage.removeItem(STORAGE_REGION_STATS_KEY);
    localStorage.removeItem(STORAGE_REGION_STATS_TIME_KEY);
    localStorage.removeItem(STORAGE_TAXONOMY_KEY);
    localStorage.removeItem(STORAGE_TAXONOMY_TIME_KEY);
    localStorage.removeItem("taiwan_birds_taxonomy_cache_v2");
    localStorage.removeItem("taiwan_birds_taxonomy_time_v2");
    localStorage.removeItem("taiwan_birds_taxonomy_cache");
    localStorage.removeItem("taiwan_birds_taxonomy_time");
    Object.values(TAB_KEYS).forEach(keys => {
      localStorage.removeItem(keys.obs);
      localStorage.removeItem(keys.time);
      localStorage.removeItem(keys.days);
    });
    // Clean up old v1 cache keys
    localStorage.removeItem("taiwan_birds_recent_obs_cache");
    localStorage.removeItem("taiwan_birds_recent_last_fetch_time");
    localStorage.removeItem("taiwan_birds_notable_obs_cache");
    localStorage.removeItem("taiwan_birds_notable_last_fetch_time");
    setApiKeySavedMsg("API Key 已清除。觀測功能已停用。");
    setTimeout(() => setApiKeySavedMsg(''), 3000);
  };

  // Accordion Toggle
  const toggleSpecies = (speciesCode) => {
    const nextExpanded = new Set(expandedSpecies);
    if (nextExpanded.has(speciesCode)) {
      nextExpanded.delete(speciesCode);
    } else {
      nextExpanded.add(speciesCode);
    }
    setExpandedSpecies(nextExpanded);
  };

  // Extract county name for a sighting
  const getSightingCounty = (sighting) => {
    if (!sighting) return '';
    if (sighting.subnational1Code && TW_REGION_MAP[sighting.subnational1Code]) {
      return TW_REGION_MAP[sighting.subnational1Code];
    }
    const loc = sighting.locName || '';
    for (const r of TW_REGIONS) {
      if (loc.includes(r.code) || loc.includes(r.name)) return r.name;
      if (r.name.startsWith('台') && loc.includes(r.name.replace('台', '臺'))) return r.name;
      if (r.name.startsWith('臺') && loc.includes(r.name.replace('臺', '台'))) return r.name;
    }
    return cleanLocationName(loc) || loc;
  };

  // Group observations by species
  const getGroupedSpeciesList = (observations, tab = activeTab) => {
    const grouped = {};
    observations.forEach(obs => {
      const code = obs.speciesCode;
      if (!grouped[code]) {
        grouped[code] = {
          speciesCode: obs.speciesCode,
          comNameZh: obs.comNameZh,
          comNameEn: obs.comNameEn,
          sciName: obs.sciName,
          sightings: []
        };
      }
      grouped[code].sightings.push(obs);
    });

    const groupedArray = Object.values(grouped);

    groupedArray.forEach(sp => {
      sp.sightings.sort((a, b) => new Date(b.obsDt) - new Date(a.obsDt));
    });

    if (tab === 'recent') {
      // 最近觀察:
      // 1st Priority Key = 觀測點位次數 (ascending / 由少到多)
      // 2nd Priority Key = 縣市名稱 (ascending / 字典序)
      // 3rd Priority Key = 最新觀測時間 (descending / 由新到舊)
      groupedArray.sort((a, b) => {
        // 1st Key: Sightings count ascending
        const countDiff = a.sightings.length - b.sightings.length;
        if (countDiff !== 0) return countDiff;

        // 2nd Key: County name ascending
        const aCounty = getSightingCounty(a.sightings[0]);
        const bCounty = getSightingCounty(b.sightings[0]);
        const countyComp = aCounty.localeCompare(bCounty, 'zh-Hant');
        if (countyComp !== 0) return countyComp;

        // 3rd Key: Latest date (obsDt) descending
        const aLatest = new Date(a.sightings[0].obsDt);
        const bLatest = new Date(b.sightings[0].obsDt);
        return bLatest - aLatest;
      });
    } else {
      // 稀有種快報: sort by latest date descending (most recent first)
      groupedArray.sort((a, b) => {
        const aLatest = new Date(a.sightings[0].obsDt);
        const bLatest = new Date(b.sightings[0].obsDt);
        return bLatest - aLatest;
      });
    }

    return groupedArray;
  };

  const formatTime = (isoString) => {
    if (!isoString) return '無紀錄';
    const date = new Date(isoString);
    return `${date.getMonth() + 1}/${date.getDate()} ${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`;
  };

  const cleanLocationName = (locName) => {
    if (!locName) return '';
    let clean = locName.replace(/\s*\([\d.-]+,\s*[\d.-]+\)/g, '');
    clean = clean.replace(/\s*\([\d.-]+,[\d.-]+\)/g, '');
    const hasChinese = /[\u4e00-\u9fa5]/.test(clean);
    if (!hasChinese) return clean.trim();
    const parenMatches = clean.match(/\(([^)]*[\u4e00-\u9fa5][^)]*)\)/);
    if (parenMatches && parenMatches[1]) return parenMatches[1].trim();
    clean = clean.replace(/\([^)]*[a-zA-Z]{2,}[^)]*\)/g, '');
    const parts = clean.split(/\s*(?:\/|--)\s*/);
    for (let part of parts) {
      if (/[\u4e00-\u9fa5]/.test(part)) {
        const chineseMatch = part.match(/[\u4e00-\u9fa5]+/g);
        if (chineseMatch) return chineseMatch.join('');
        return part.trim();
      }
    }
    const chineseBlocks = clean.match(/[\u4e00-\u9fa5]+/g);
    if (chineseBlocks) return chineseBlocks.join('');
    return clean.trim();
  };

  const renderAccordionList = (observations) => {
    const groupedSpecies = getGroupedSpeciesList(observations);

    if (groupedSpecies.length === 0) {
      return (
        <div className="empty-state">
          <Compass size={48} style={{ color: 'var(--text-muted)' }} />
          <h3>查無觀測紀錄</h3>
          <p>在過去 {tabState[activeTab].days} 天內，eBird 系統尚未在台灣地區登錄任何觀測紀錄。</p>
        </div>
      );
    }

    return (
      <main className="species-list-container">
        {groupedSpecies.map((sp) => {
          const isExpanded = expandedSpecies.has(sp.speciesCode);
          return (
            <div
              className={`species-accordion-item ${isExpanded ? 'is-open' : ''} ${activeTab === 'notable' && !sp.sightings[0].obsReviewed ? 'unreviewed' : ''}`}
              key={sp.speciesCode}
            >
              <div
                className="species-accordion-header"
                onClick={() => toggleSpecies(sp.speciesCode)}
              >
                <div className="species-primary-info">
                  <div className="species-name-row">
                    <span className="species-chinese">{sp.comNameZh}</span>
                    <span className="species-english">{sp.comNameEn}</span>
                    <span className="species-scientific">({sp.sciName})</span>
                  </div>
                  <div className="species-subtitle-row">
                    <span className="species-latest-date">
                      {sp.sightings[0].obsDt}
                    </span>
                    <span className="species-latest-separator">·</span>
                    <span className="species-latest-loc" title={sp.sightings[0].locName}>
                      {cleanLocationName(sp.sightings[0].locName)}
                    </span>
                  </div>
                </div>
                <div className="species-meta-info">
                  <span className="sightings-counter-pill">
                    {sp.sightings.length} 次觀測點
                  </span>
                  <button className="accordion-arrow-btn">
                    {isExpanded ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
                  </button>
                </div>
              </div>
              {isExpanded && (
                <div className="species-accordion-content">
                  <div className="sightings-table-container">
                    <table className="sightings-table">
                      <thead>
                        <tr>
                          <th>觀測日期</th>
                          <th>發現地點</th>
                          <th style={{ textAlign: 'right' }}>數量</th>
                        </tr>
                      </thead>
                      <tbody>
                        {sp.sightings.map((sighting, sIdx) => {
                          const mapUrl = `https://www.google.com/maps/search/?api=1&query=${sighting.lat},${sighting.lng}`;
                          return (
                            <tr key={`${sighting.subId}-${sIdx}`} className={activeTab === 'notable' && !sighting.obsReviewed ? 'unreviewed-row' : ''}>
                              <td className="td-date">
                                <Calendar size={14} style={{ marginRight: '0.4rem', verticalAlign: 'middle', color: 'var(--text-muted)' }} />
                                <span>{sighting.obsDt}</span>
                                {activeTab === 'notable' && !sighting.obsReviewed && <span className="unreviewed-badge">未審核</span>}
                              </td>
                              <td className="td-location" title={sighting.locName}>
                                <a
                                  href={mapUrl}
                                  target="_blank"
                                  rel="noopener noreferrer"
                                  className="location-link"
                                >
                                  <MapPin size={14} className="location-nav-icon" />
                                  <span className="location-name-text">{sighting.locName}</span>
                                </a>
                              </td>
                              <td className="td-count" style={{ textAlign: 'right' }}>
                                <span className="count-tag">
                                  {sighting.howMany ? `${sighting.howMany} 隻` : '出現'}
                                </span>
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </main>
    );
  };

  const toggleCounty = (countyName) => {
    setExpandedCounty(prev => (prev === countyName ? null : countyName));
  };

  // Group observations by county/region for Recent tab
  const getGroupedCountyList = (observations) => {
    const countyMap = {};

    observations.forEach(obs => {
      const county = getSightingCounty(obs);
      if (!countyMap[county]) {
        countyMap[county] = {
          countyName: county,
          speciesSet: new Set(),
          sightings: []
        };
      }
      countyMap[county].speciesSet.add(obs.speciesCode);
      countyMap[county].sightings.push(obs);
    });

    const countyList = Object.values(countyMap).map(c => {
      // Sort sightings inside each county by obsDt descending (most recent first)
      const sortedSightings = [...c.sightings].sort((a, b) => new Date(b.obsDt) - new Date(a.obsDt));

      // Group by species inside county, sorting species by their latest obsDt descending
      const speciesMap = {};
      sortedSightings.forEach(s => {
        const code = s.speciesCode;
        if (!speciesMap[code]) {
          speciesMap[code] = {
            speciesCode: s.speciesCode,
            comNameZh: s.comNameZh,
            comNameEn: s.comNameEn,
            sciName: s.sciName,
            sightings: []
          };
        }
        speciesMap[code].sightings.push(s);
      });

      const speciesList = Object.values(speciesMap).sort((a, b) => {
        const aLatest = new Date(a.sightings[0].obsDt);
        const bLatest = new Date(b.sightings[0].obsDt);
        return bLatest - aLatest;
      });

      return {
        countyName: c.countyName,
        totalSpecies: c.speciesSet.size,
        totalSightings: c.sightings.length,
        latestObsDt: sortedSightings[0] ? sortedSightings[0].obsDt : '',
        speciesList,
      };
    });

    // Sort county list alphabetically / by TW_REGIONS order
    countyList.sort((a, b) => a.countyName.localeCompare(b.countyName, 'zh-Hant'));

    return countyList;
  };

  const renderCountyAccordionList = (observations) => {
    const countyList = getGroupedCountyList(observations);

    if (countyList.length === 0) {
      return (
        <div className="empty-state">
          <Compass size={48} style={{ color: 'var(--text-muted)' }} />
          <h3>查無觀測紀錄</h3>
          <p>在過去 {tabState[activeTab].days} 天內，尚未在您選擇的縣市登錄任何觀測紀錄。</p>
        </div>
      );
    }

    return (
      <main className="species-list-container">
        {countyList.map((c) => {
          const isExpanded = expandedCounty === c.countyName;
          return (
            <div
              className={`species-accordion-item ${isExpanded ? 'is-open' : ''}`}
              key={c.countyName}
            >
              <div
                className="species-accordion-header"
                onClick={() => toggleCounty(c.countyName)}
              >
                <div className="species-primary-info">
                  <div className="species-name-row" style={{ alignItems: 'center' }}>
                    <MapPin size={18} style={{ color: 'var(--accent-secondary)', marginRight: '0.2rem', flexShrink: 0 }} />
                    <span className="species-chinese" style={{ fontSize: '1.2rem', fontWeight: '700' }}>{c.countyName}</span>
                    <span className="sightings-counter-pill" style={{ marginLeft: '0.6rem' }}>
                      共 {c.totalSpecies} 種鳥類
                    </span>
                  </div>
                  <div className="species-subtitle-row" style={{ marginTop: '0.25rem' }}>
                    <span className="species-latest-date">
                      最新紀錄: {c.latestObsDt || '無'}
                    </span>
                    <span className="species-latest-separator">·</span>
                    <span className="species-latest-loc">
                      {c.totalSightings} 個觀測點位
                    </span>
                  </div>
                </div>
                <div className="species-meta-info">
                  <button className="accordion-arrow-btn">
                    {isExpanded ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
                  </button>
                </div>
              </div>

              {isExpanded && (
                <div className="species-accordion-content">
                  <div className="sightings-table-container">
                    <table className="sightings-table">
                      <thead>
                        <tr>
                          <th>觀測時間 / 鳥種</th>
                          <th>發現地點</th>
                          <th style={{ textAlign: 'right' }}>數量</th>
                        </tr>
                      </thead>
                      <tbody>
                        {c.speciesList.map((sp) => {
                          return sp.sightings.map((sighting, sIdx) => {
                            const mapUrl = `https://www.google.com/maps/search/?api=1&query=${sighting.lat},${sighting.lng}`;
                            return (
                              <tr key={`${sighting.subId}-${sp.speciesCode}-${sIdx}`}>
                                <td className="td-date">
                                  <div style={{ fontWeight: '600', color: 'var(--text-primary)', marginBottom: '0.15rem' }}>
                                    <span style={{ color: 'var(--accent-primary)', marginRight: '0.4rem' }}>{sp.comNameZh}</span>
                                    <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)', fontWeight: '400' }}>({sp.comNameEn})</span>
                                  </div>
                                  <div style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                                    <Calendar size={13} style={{ marginRight: '0.3rem', verticalAlign: 'middle', color: 'var(--text-muted)' }} />
                                    <span>{sighting.obsDt}</span>
                                  </div>
                                </td>
                                <td className="td-location" title={sighting.locName}>
                                  <a
                                    href={mapUrl}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="location-link"
                                  >
                                    <MapPin size={14} className="location-nav-icon" />
                                    <span className="location-name-text">{sighting.locName}</span>
                                  </a>
                                </td>
                                <td className="td-count" style={{ textAlign: 'right' }}>
                                  <span className="count-tag">
                                    {sighting.howMany ? `${sighting.howMany} 隻` : '出現'}
                                  </span>
                                </td>
                              </tr>
                            );
                          });
                        })}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </main>
    );
  };

  const renderTabContent = () => {
    const current = tabState[activeTab];

    // Show API key prompt only if no data loaded and no API key
    if (!apiKey && (!current.observations || current.observations.length === 0)) {
      return (
        <section className="glass-panel warning-overlay-panel">
          <div className="warning-content">
            <AlertTriangle size={54} className="pulse-warning" style={{ color: 'var(--accent-warning)' }} />
            <h2>需要 eBird API 金鑰</h2>
            <p>
              為了載入台灣鳥類觀測清單，請先點擊右上方設定圖示（<Settings size={18} style={{ display: 'inline', verticalAlign: 'middle', margin: '0 0.2rem' }} />）輸入您的個人 eBird API Key。
            </p>
            <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginTop: '-0.5rem' }}>
              金鑰申請完全免費，並只會安全地儲存在您目前的瀏覽器本地快取中。
            </p>
          </div>
        </section>
      );
    }

    const isNotable = activeTab === 'notable';

    // Recent tab: require at least 1 selected region
    if (!isNotable && selectedRegions.length === 0) {
      return (
        <section className="glass-panel warning-overlay-panel">
          <div className="warning-content">
            <AlertTriangle size={54} className="pulse-warning" style={{ color: 'var(--accent-warning)' }} />
            <h2>請先選擇縣市</h2>
            <p>
              請點擊右上方設定圖示（<Settings size={18} style={{ display: 'inline', verticalAlign: 'middle', margin: '0 0.2rem' }} />），至少選擇 1 個縣市後才能查詢最近觀察資料。
            </p>
          </div>
        </section>
      );
    }

    let observationsToDisplay = current.observations;
    if (!isNotable && selectedRegions.length > 0) {
      observationsToDisplay = current.observations.filter(obs => isObsInSelectedRegions(obs, selectedRegions));
    }

    const groupedSpecies = getGroupedSpeciesList(observationsToDisplay);

    return (
      <>
        {/* Control Panel with last update inline */}
        <section className="glass-panel">
          <div className="controls-grid">
            <div className="select-container">
              <label htmlFor="date-select" className="select-label">
                觀測區間
                <span className="last-update-text">
                  <span className="pulse-dot"></span>
                  最後更新: {formatTime(current.lastUpdated)}
                </span>
              </label>
              <select
                id="date-select"
                value={current.days}
                onChange={(e) => updateTab(activeTab, { days: Number(e.target.value) })}
                className="custom-select"
              >
                {!isNotable ? (
                  <>
                    <option value={1}>過去 1 天 (預設)</option>
                    <option value={2}>過去 2 天</option>
                    <option value={3}>過去 3 天</option>
                    <option value={30}>累積 30 天</option>
                  </>
                ) : (
                  <>
                    <option value={3}>過去 3 天 (預設)</option>
                    <option value={7}>過去 7 天</option>
                    <option value={14}>過去 14 天</option>
                    <option value={30}>過去 30 天</option>
                  </>
                )}
              </select>
            </div>
          </div>
        </section>

        {/* Selected region capsules (recent tab only) */}
        {!isNotable && selectedRegions.length > 0 && (
          <div className="region-capsules-bar">
            {selectedRegions.map(code => (
              <span key={code} className="region-capsule">
                {TW_REGION_MAP[code] || code}
              </span>
            ))}
          </div>
        )}

        {/* Info Section */}
        <div className="stats-ribbon">
          <div className="stats-text">
            {isNotable ? (
              <>
                在過去 <span className="stats-count">{current.days}</span> 天內，觀測到
                <span className="stats-count">{groupedSpecies.length}</span> 種罕見鳥類
              </>
            ) : (
              <>
                在過去 <span className="stats-count">{current.days}</span> 天內，您選擇的縣市觀測到 <span className="stats-count">{groupedSpecies.length}</span> 種鳥
                <br />
                {new Date().getMonth() + 1}月全台共計觀察 <span className="stats-count">{monthSpeciesCount ?? '—'}</span>種鳥
              </>
            )}
          </div>
        </div>

        {/* Accordion List */}
        {current.loading ? (
          <div className="loading-state">
            <div className="hourglass-loader" style={{ padding: '1rem 0' }}>
              <Hourglass size={48} className="pulse-hourglass" style={{ color: 'var(--accent-secondary)' }} />
            </div>
            <p>正在搜尋與整合觀測紀錄，請稍候...</p>
          </div>
        ) : current.error ? (
          <div className="error-state">
            <AlertTriangle size={48} style={{ color: '#ef4444' }} />
            <h3>載入失敗</h3>
            <p>{current.error}</p>
            <button className="btn-primary" onClick={handleSearchClick}>重試</button>
          </div>
        ) : isNotable ? (
          renderAccordionList(observationsToDisplay)
        ) : (
          renderCountyAccordionList(observationsToDisplay)
        )}
      </>
    );
  };

  return (
    <div className="app-container">
      {/* Header */}
      <header className="glass-panel app-header">
        <div className="brand-wrapper">
          <div className="logo-icon">
            <span>e</span>
          </div>
          <div className="title-section">
            <div className="title-row-container">
              <h1>eBird台灣鳥類查詢</h1>
            </div>
            <p className="header-credit">Sam Tsai 製作，歡迎公益使用</p>
          </div>
        </div>

        <div className="header-actions">
          <button
            className={`btn-icon ${showSettings ? 'active-btn' : ''}`}
            onClick={() => showSettings ? handleCloseSettings() : handleOpenSettings()}
            title="設定"
          >
            <Settings size={20} />
          </button>
          <button
            className="btn-icon"
            onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
            title="切換主題"
          >
            {theme === 'dark' ? <Sun size={20} /> : <Moon size={20} />}
          </button>
        </div>
      </header>

      {/* Settings Panel — full-screen popup overlay */}
      {showSettings && (
        <div className="settings-overlay">
          <section className="settings-popup">
            <div className="settings-popup-header">
              <h2>設定</h2>
            </div>
            <div className="settings-popup-body">

              {/* Section 1: API Key */}
              <div className={`settings-accordion-card ${openSettingsSections.key ? 'is-open' : ''}`}>
                <div
                  className="settings-accordion-header"
                  onClick={() => toggleSettingsSection('key')}
                >
                  <div className="settings-accordion-title">
                    <Key size={18} style={{ color: 'var(--accent-secondary)' }} />
                    <h3>eBird API 金鑰設定</h3>
                  </div>
                  <div className="settings-accordion-meta">
                    <span className={`settings-badge ${apiKey ? 'badge-active' : 'badge-warning'}`}>
                      {apiKey ? '已設定' : '未設定'}
                    </span>
                    {openSettingsSections.key ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
                  </div>
                </div>
                {openSettingsSections.key && (
                  <div className="settings-accordion-body">
                    <p className="panel-desc">
                      請輸入您的個人 eBird API Key。您可以在{' '}
                      <a
                        href="https://ebird.org/api/keygen"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-link"
                      >
                        eBird 官方網站申請金鑰
                      </a>
                      （需註冊 eBird 免費帳號）。
                    </p>
                    <div className="api-key-input-group" style={{ marginTop: '0.75rem' }}>
                      <input
                        type="password"
                        placeholder="請貼上您的 eBird API Key..."
                        value={inputApiKey}
                        onChange={(e) => setInputApiKey(e.target.value)}
                        className="api-key-input"
                      />
                      <button
                        className="btn-save-api-key"
                        onClick={() => saveApiKey()}
                      >
                        儲存金鑰
                      </button>
                      {apiKey && (
                        <button
                          className="btn-clear-api-key"
                          onClick={clearApiKey}
                          title="從本地快取移除金鑰並清空資料"
                        >
                          清除金鑰
                        </button>
                      )}
                    </div>
                    {apiKeySavedMsg && (
                      <div className="save-success-msg" style={{ marginTop: '0.5rem' }}>
                        <CheckCircle size={14} style={{ color: 'var(--accent-primary)' }} />
                        <span>{apiKeySavedMsg}</span>
                      </div>
                    )}
                  </div>
                )}
              </div>

              {/* Section 2: Region Selection */}
              <div className={`settings-accordion-card ${openSettingsSections.region ? 'is-open' : ''}`}>
                <div
                  className="settings-accordion-header"
                  onClick={() => toggleSettingsSection('region')}
                >
                  <div className="settings-accordion-title">
                    <MapPin size={18} style={{ color: 'var(--accent-secondary)' }} />
                    <h3>觀察縣市設定</h3>
                  </div>
                  <div className="settings-accordion-meta">
                    <span className={`settings-badge ${selectedRegions.length > 0 ? 'badge-active' : 'badge-warning'}`}>
                      {selectedRegions.length === 0 ? '未選擇' : `已選 ${selectedRegions.length}/6 縣市`}
                    </span>
                    {openSettingsSections.region ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
                  </div>
                </div>
                {openSettingsSections.region && (
                  <div className="settings-accordion-body">
                    <p className="panel-desc">
                      選擇要查詢的縣市（最多 6 個）。系統將會根據您選取的縣市即時篩選與更新觀測資料。
                    </p>
                    <div className="region-select-grid">
                      {TW_REGIONS.map(r => (
                        <button
                          key={r.code}
                          className={`region-chip ${selectedRegions.includes(r.code) ? 'region-chip-selected' : ''}`}
                          onClick={() => toggleRegion(r.code)}
                          disabled={!selectedRegions.includes(r.code) && selectedRegions.length >= 6}
                        >
                          {r.name}
                        </button>
                      ))}
                    </div>
                    <p className="panel-desc" style={{ fontSize: '0.8rem', marginTop: '0.5rem', color: selectedRegions.length === 0 ? 'var(--accent-warning)' : 'var(--text-muted)' }}>
                      {selectedRegions.length === 0
                        ? '請至少選擇 1 個縣市，否則無法查詢最近觀察資料'
                        : `已選 ${selectedRegions.length}/6 個縣市`}
                    </p>
                  </div>
                )}
              </div>

              {/* Section 3: Update Bird Data */}
              <div className={`settings-accordion-card ${openSettingsSections.update ? 'is-open' : ''}`}>
                <div
                  className="settings-accordion-header"
                  onClick={() => toggleSettingsSection('update')}
                >
                  <div className="settings-accordion-title">
                    <RotateCw size={18} style={{ color: 'var(--accent-secondary)' }} />
                    <h3>更新鳥類名單</h3>
                  </div>
                  <div className="settings-accordion-meta">
                    <span className="settings-badge">
                      即時抓取 eBird
                    </span>
                    {openSettingsSections.update ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
                  </div>
                </div>
                {openSettingsSections.update && (
                  <div className="settings-accordion-body">
                    <p className="panel-desc">
                      從 eBird 即時抓取最新資料。最近觀察會查詢所選縣市，稀有種快報查詢全台灣。
                    </p>
                    {!apiKey && (
                      <p className="panel-desc" style={{ color: 'var(--accent-warning)', marginTop: '0.25rem' }}>
                        請先在上方設定 eBird API 金鑰以啟用線上更新功能。
                      </p>
                    )}
                    {apiKey && (
                      <div style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap', marginTop: '0.75rem' }}>
                        <button
                          className="btn-primary"
                          onClick={() => { setActiveTab('recent'); setShowSettings(false); setTimeout(() => setShowUpdateConfirm(true), 100); }}
                          disabled={tabState.recent.loading || selectedRegions.length === 0}
                          style={{ width: 'auto', padding: '0.5rem 1.2rem' }}
                        >
                          <RotateCw size={16} className={tabState.recent.loading ? "spin" : ""} />
                          <span>{tabState.recent.loading ? "更新中..." : "更新最近觀察"}</span>
                        </button>
                        <button
                          className="btn-primary"
                          onClick={() => { setActiveTab('notable'); setShowSettings(false); setTimeout(() => setShowUpdateConfirm(true), 100); }}
                          disabled={tabState.notable.loading}
                          style={{ width: 'auto', padding: '0.5rem 1.2rem' }}
                        >
                          <RotateCw size={16} className={tabState.notable.loading ? "spin" : ""} />
                          <span>{tabState.notable.loading ? "更新中..." : "更新稀有種快報"}</span>
                        </button>
                      </div>
                    )}
                  </div>
                )}
              </div>

            </div>
            <div className="settings-popup-footer">
              <button
                className="btn-primary"
                style={{ width: 'auto', padding: '0.6rem 2.5rem', margin: '0 auto' }}
                onClick={() => handleCloseSettings()}
                disabled={selectedRegions.length === 0 && activeTab === 'recent'}
              >
                回到主畫面
              </button>
            </div>
          </section>
        </div>
      )}

      {/* Tab Bar */}
      <div className="tab-bar">
        {Object.entries(TAB_LABELS).map(([key, label]) => (
          <button
            key={key}
            className={`tab-btn ${activeTab === key ? 'tab-active' : ''}`}
            onClick={() => setActiveTab(key)}
          >
            {label}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      {renderTabContent()}

      {/* Update confirmation dialog */}
      {showUpdateConfirm && (
        <div className="modal-overlay" onClick={() => setShowUpdateConfirm(false)}>
          <div className="modal-dialog" onClick={e => e.stopPropagation()}>
            <AlertTriangle size={36} style={{ color: 'var(--accent-warning)' }} />
            <h3>確認更新</h3>
            <p>
              {activeTab === 'recent'
                ? '更新資料需要查詢所選縣市的 eBird 紀錄，等待時間比較長。是否繼續？'
                : '更新資料需要從 eBird 抓取最新紀錄，等待時間比較長。是否繼續？'}
            </p>
            <div className="modal-dialog-buttons">
              <button className="btn-cancel" onClick={() => setShowUpdateConfirm(false)}>取消</button>
              <button className="btn-primary" onClick={confirmUpdate}>確認更新</button>
            </div>
          </div>
        </div>
      )}

      {/* Inline styles */}
      <style>{`
        .spin {
          animation: spin-anim 1s linear infinite;
        }
        @keyframes spin-anim {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
        .pulse-warning {
          animation: warning-pulse 2s infinite;
        }
        @keyframes warning-pulse {
          0%, 100% { transform: scale(1); opacity: 1; }
          50% { transform: scale(1.08); opacity: 0.8; }
        }
      `}</style>
    </div>
  );
}